name: Add Changeset to Dependabot PRs
description: Automatically add a changeset to Dependabot pull requests
inputs:
  pkgName:
    description: 'The package name to create a changeset for'
    required: true
  releaseType:
    description: 'The type of release to create (patch, minor, major)'
    required: false
    default: 'patch'
  prefix:
    default: '[add changeset]'
    description: 'The prefix to use for the changeset commit message'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - shell: bash
      run: npm install @changesets/write
    - name: Get first commit message and create changeset
      uses: actions/github-script@v7
      env:
        COMMIT_PREFIX: ${{ inputs.prefix }}
        PACKAGE_NAME: ${{ inputs.pkgName }}
        RELEASE_TYPE: ${{ inputs.releaseType }}
      with:
        script: |
          const { default: writeChangeset } = require('@changesets/write');
          const { data: commits } = await github.rest.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });

          // Check if any commit message starts with the specified prefix
          const hasChangesetCommit = commits.some(c => c.commit.message.startsWith(process.env.COMMIT_PREFIX));
          if (hasChangesetCommit) {
            console.log('PR already contains a changeset commit. Skipping changeset creation.');
            return;
          }

          // Get a commit message from the first line of the commit in the PR that dependabot created
          const firstCommit = commits[0];
          const commitMessage = firstCommit.commit.message.split('\n')[0];
          console.log('Commit message:', commitMessage);

          const id = await writeChangeset(
            {
              summary: commitMessage,
              releases: [
                {
                  name: process.env.PACKAGE_NAME,
                  type: process.env.RELEASE_TYPE
                }
              ]
            },
            process.cwd(),
          );

          console.log(`Created changeset with ID: ${id}`);
    - name: Commit changeset
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '${{ inputs.prefix }} dependabot update'
        file_pattern: '.changeset/*.md'
